name: edc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - langchain-openai
  - pdfplumber